### PR TITLE
[WIP] Add travis-cargo to CI and enable code coverage

### PR DESCRIPTION
**Pull request by sunchao**

### CODE REVIEW

**Comment by andygrove** [comment]
This seems close! It currently fails on

```
Uploading coverage
Usage: kcov [OPTIONS] out-dir in-file [args...]

```

**Comment by sunchao** [comment]
OK. I'll see how to fix that...

**Comment by andygrove** [comment]
Thanks for persevering @sunchao ! I see code coverage results on coveralls now :+1: :100:

**Comment by sunchao** [comment]
Nice. Finally got it working :)

**Pull request merged**
