### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by sunchao**
This tries to add CI for the project. It may requires some setup on travis-ci.org though.

### CODE REVIEW

**Comment by sunchao** [comment]
@andygrove Can you activate this repo on travis-ci.org so that travis job can be triggered?

**Comment by andygrove** [comment]
Awesome. Thanks! I merged this first PR to trigger a build on travis (I just set that up).

**Comment by andygrove** [comment]
The build fails because parquet-rs 0.1.0 needs thrift ... hopefully 0.2.0 fixes this

**Comment by sunchao** [comment]
Oops. Forgot about that. Yes 0.2.0 should fix it. Thanks for merging!

**Comment by andygrove** [comment]
travis build passes now but fails at end with "error: no such subcommand: `coveralls`"

**Comment by sunchao** [comment]
I think I know how to fix it. Will post another PR.

**Pull request merged**
