### PR TITLE
Sum Aggregate function

### PR DESCRIPTION
**Pull request by hntd187**
This is incomplete, I have to add more testing and clean up as some of the errors are all over the place and the type coverage isn't completely there either, but for most integer types it appears to work. I'm more also just looking to make sure I'm on the right path for how to implement this.

### CODE REVIEW

**Comment by hntd187** [comment]
Cool, I'll update to reflect that and clean my errors up a bit. What were you looking for in terms of breadth of testing for this?

**Comment by andygrove** [comment]
There are some aggregate tests in https://github.com/datafusion-rs/datafusion/blob/master/tests/all_types.rs that test all supported types for min/max ... you could create some new ones for sum based on these.

**Comment by hntd187** [comment]
I messed up my branch ugh, give me a minute, I'll try and sort this out

**Comment by andygrove** [comment]
Thanks @hntd187  ! I wasn't sure if you were done with this or not but it looks good so I went ahead and merged.

**Comment by hntd187** [comment]
Thanks @andygrove , I added some very rough windows support too. The code should at least compile and run tests on windows now as well.

**Pull request merged**
